spring.datasource.url=jdbc:postgresql://localhost:5433/appmelinabit
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=melinabit.suporte@gmail.com
spring.mail.password=pogxqzajwxtpbuoi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true