spring.datasource.url=jdbc:postgresql://db-melinabit:5432/melinabit_db
spring.datasource.username=AppMelinabit
spring.datasource.password=Jeffbl1980

# Configurações do Hibernate para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração de Thymeleaf (já que você tem pastas templates/static)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Porta padrão
server.port=8080
# Configuração de E-mail (Exemplo genérico para destravar o Spring)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
